version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: webhook_webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3381:3381"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: webhook_php_fpm
    working_dir: /application
    volumes:
      - .:/application
